Coders = set(["Arnav","Gornash","Mani","Parul"])
Analysts = set(["Krish","Mehak","Shiv","Gornash","Mani"])
print("Coders : ", Coders)
print("Analysts : ", Analysts)
print("People working as coders as well as Analysts : ", Coders.intersection(Analysts))
print("People working as Coders or Analysts : ", Coders.union(Analysts))
print("People working as Coders but not Analysts : ", Coders.difference(Analysts))
print("People working as Analysts but not Coders : ", Analysts.difference(Coders))
print("People working in only one of the groups : ", Coders.symmetric_difference(Analysts))
